Change name of build-and-test workflow to cmake_multiplatform_ci.yml. Try including windows and macos jobs.

diff --git a/.github/workflows/cmake_multiplatform_ci.yml b/.github/workflows/cmake_multiplatform_ci.yml
--- a/.github/workflows/cmake_multiplatform_ci.yml
+++ b/.github/workflows/cmake_multiplatform_ci.yml
@@ -15,16 +15,26 @@ jobs:
       fail-fast: false
 
       matrix:
-        os: [ubuntu-latest] # I removed windows since the workflow was failing on windows, but will add it back later
+        os: [ubuntu-latest, windows-latest, macos-latest] # I removed windows since the workflow was failing on windows, but will add it back later
         build_type: [Release]
-        c_compiler: [gcc, clang]
+        #c_compiler: [gcc, clang, cl]
         include:
           - os: ubuntu-latest
             c_compiler: gcc
             cpp_compiler: g++
+            build_type: Release
           - os: ubuntu-latest
             c_compiler: clang
             cpp_compiler: clang++
+            build_type: Release
+          - os: windows-latest
+            c_compiler: cl
+            cpp_compiler: cl
+            build_type: Release
+          - os: macos-latest
+            c_compiler: clang
+            cpp_compiler: clang++
+            build_type: Release
 
     steps:
     - uses: actions/checkout@v4
@@ -52,4 +62,4 @@ jobs:
 
     - name: Print test log on failure
       if: failure()
-      run: cat ${{ steps.strings.outputs.build-output-dir }}/Testing/Temporary/LastTest.log || tru
+      run: cat ${{ steps.strings.outputs.build-output-dir }}/Testing/Temporary/LastTest.log || true
