Correct path to error log for Windows ci. Replace remaining instances of M_PI. Add flags to enforce MD linking on Windows.

diff --git a/.github/workflows/cmake_multiplatform_ci.yml b/.github/workflows/cmake_multiplatform_ci.yml
--- a/.github/workflows/cmake_multiplatform_ci.yml
+++ b/.github/workflows/cmake_multiplatform_ci.yml
@@ -62,4 +62,12 @@ jobs:
 
     - name: Print test log on failure
       if: failure()
-      run: cat ${{ steps.strings.outputs.build-output-dir }}/Testing/Temporary/LastTest.log || true
+      run: |
+        if [[ "$RUNNER_OS" == "Windows" ]]; then
+          echo "Running on Windows"
+          type ${{ steps.strings.outputs.build-output-dir }}\Testing\Temporary\LastTest.log || echo "Log file not found"
+        else
+          echo "Running on $RUNNER_OS"
+          cat ${{ steps.strings.outputs.build-output-dir }}/Testing/Temporary/LastTest.log || echo "Log file not found"
+        fi
+    
